name: Update verification tasks
on:
  push:
    paths:
      - "data/clean/turism_gov_ro/uniform/ttmo_gov_list.csv"
  workflow_dispatch:

jobs:
  update-verification-tasks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.COMMIT_TRIGGER }}
          fetch-depth: 2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - uses: actions/cache@v2
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ hashFiles('scripts/turism_gov_ro/verification_tasks/requirements.txt') }}

      - name: Install the requirements
        run: pip install --upgrade --upgrade-strategy eager -r scripts/turism_gov_ro/verification_tasks/requirements.txt

      - name: Update the verification tasks and write deleted and modified tasks to markdown files
        id: verify
        run: |
          git show HEAD~1:data/clean/turism_gov_ro/uniform/ttmo_gov_list.csv > data/clean/turism_gov_ro/uniform/ttmo_gov_list.old.csv
          python scripts/turism_gov_ro/verification_tasks/generate_verification_task_dataset.py
          rm -f data/clean/turism_gov_ro/uniform/ttmo_gov_list.old.csv
          if [[ -f "issue.md" ]]; then
            echo "::set-output name=should_create_issue::true"
          fi
      
      - name: Create an issue for the new and removed rows
        if: steps.verify.outputs.should_create_issue
        uses: peter-evans/create-issue-from-file@v3
        with:
          title: New or removed rows in the clean dataset
          content-filepath: issue.md
          labels: |
            automated
            important

      - name: Remove the issue file
        run: |
          if [[ -f "issue.md" ]]; then
            rm -f issue.md
          fi

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          branch: update-verification-tasks
          commit-message: Update verification tasks
          author: github-actions <github-actions@github.com>
          delete-branch: true
          title: Update verification tasks
          labels: |
            automated
            verification
            new task
          assignees: archblob
          reviewers: archblob
          draft: false
          body: |
            This is an automated PR to update the verification tasks.
            Please review the changes and merge if everything is correct.